In [8]:
#import libs
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [9]:
paragraph="""
Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]

In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. A little over 1,000 people were killed, according to official records, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[11] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[e] While his policies as chief minister, which were credited for encouraging economic growth, were praised, Modi's administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f] In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment, and it reduced spending on healthcare, education, and social-welfare programmes. Modi began a high-profile sanitation campaign, controversially initiated the 2016 demonetisation of high-denomination banknotes and introduced the Goods and Services Tax, and weakened or abolished environmental and labour laws.

Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan. The airstrike failed,[14][15] and the deaths of six Indian personnel to friendly fire was later revealed: but the action had nationalist appeal.[16] Modi's party won the 2019 general election which followed.[17] In its second term, his administration revoked the special status of Jammu and Kashmir, an Indian-administered portion of the disputed Kashmir region,[18][19] and introduced the Citizenship Amendment Act, prompting widespread protests, and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs,[20][21][22] sometimes with the complicity of police forces controlled by the Modi administration.[23][24] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which 4.7 million out of 1.4 billion Indians died, according to the World Health Organization's estimates.[25][26]
"""

In [10]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jatin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [11]:
sent_text = nltk.sent_tokenize(paragraph)

In [12]:
sent_text

['\nNarendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014.',
 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation.',
 'He is the longest-serving prime minister from outside the Indian National Congress.',
 'Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do s

In [15]:
words_list = word_tokenize(paragraph)
words_list

['Narendra',
 'Damodardas',
 'Modi',
 '(',
 'Gujarati',
 ':',
 '[',
 'ˈnəɾendɾə',
 'dɑmodəɾˈdɑs',
 'ˈmodiː',
 ']',
 'ⓘ',
 ';',
 'born',
 '17',
 'September',
 '1950',
 ')',
 '[',
 'b',
 ']',
 'is',
 'an',
 'Indian',
 'politician',
 'who',
 'has',
 'served',
 'as',
 'the',
 '14th',
 'prime',
 'minister',
 'of',
 'India',
 'since',
 'May',
 '2014',
 '.',
 'Modi',
 'was',
 'the',
 'chief',
 'minister',
 'of',
 'Gujarat',
 'from',
 '2001',
 'to',
 '2014',
 'and',
 'is',
 'the',
 'Member',
 'of',
 'Parliament',
 '(',
 'MP',
 ')',
 'for',
 'Varanasi',
 '.',
 'He',
 'is',
 'a',
 'member',
 'of',
 'the',
 'Bharatiya',
 'Janata',
 'Party',
 '(',
 'BJP',
 ')',
 'and',
 'of',
 'the',
 'Rashtriya',
 'Swayamsevak',
 'Sangh',
 '(',
 'RSS',
 ')',
 ',',
 'a',
 'right',
 'wing',
 'Hindu',
 'nationalist',
 'paramilitary',
 'volunteer',
 'organisation',
 '.',
 'He',
 'is',
 'the',
 'longest-serving',
 'prime',
 'minister',
 'from',
 'outside',
 'the',
 'Indian',
 'National',
 'Congress',
 '.',
 'Modi',
 '

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jatin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [19]:
# Remove stop words
filtered_words = [word for word in words_list if word.lower() not in stopwords.words('english')]
filtered_words

['Narendra',
 'Damodardas',
 'Modi',
 '(',
 'Gujarati',
 ':',
 '[',
 'ˈnəɾendɾə',
 'dɑmodəɾˈdɑs',
 'ˈmodiː',
 ']',
 'ⓘ',
 ';',
 'born',
 '17',
 'September',
 '1950',
 ')',
 '[',
 'b',
 ']',
 'Indian',
 'politician',
 'served',
 '14th',
 'prime',
 'minister',
 'India',
 'since',
 'May',
 '2014',
 '.',
 'Modi',
 'chief',
 'minister',
 'Gujarat',
 '2001',
 '2014',
 'Member',
 'Parliament',
 '(',
 'MP',
 ')',
 'Varanasi',
 '.',
 'member',
 'Bharatiya',
 'Janata',
 'Party',
 '(',
 'BJP',
 ')',
 'Rashtriya',
 'Swayamsevak',
 'Sangh',
 '(',
 'RSS',
 ')',
 ',',
 'right',
 'wing',
 'Hindu',
 'nationalist',
 'paramilitary',
 'volunteer',
 'organisation',
 '.',
 'longest-serving',
 'prime',
 'minister',
 'outside',
 'Indian',
 'National',
 'Congress',
 '.',
 'Modi',
 'born',
 'raised',
 'Vadnagar',
 'northeastern',
 'Gujarat',
 ',',
 'completed',
 'secondary',
 'education',
 '.',
 'introduced',
 'RSS',
 'age',
 'eight',
 '.',
 'account',
 'helping',
 'father',
 'sell',
 'tea',
 'Vadnagar',
 'rail

In [20]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]

In [22]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jatin\AppData\Roaming\nltk_data...


True

In [24]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
lemmatized_words

['Narendra',
 'Damodardas',
 'Modi',
 '(',
 'Gujarati',
 ':',
 '[',
 'ˈnəɾendɾə',
 'dɑmodəɾˈdɑs',
 'ˈmodiː',
 ']',
 'ⓘ',
 ';',
 'born',
 '17',
 'September',
 '1950',
 ')',
 '[',
 'b',
 ']',
 'Indian',
 'politician',
 'served',
 '14th',
 'prime',
 'minister',
 'India',
 'since',
 'May',
 '2014',
 '.',
 'Modi',
 'chief',
 'minister',
 'Gujarat',
 '2001',
 '2014',
 'Member',
 'Parliament',
 '(',
 'MP',
 ')',
 'Varanasi',
 '.',
 'member',
 'Bharatiya',
 'Janata',
 'Party',
 '(',
 'BJP',
 ')',
 'Rashtriya',
 'Swayamsevak',
 'Sangh',
 '(',
 'RSS',
 ')',
 ',',
 'right',
 'wing',
 'Hindu',
 'nationalist',
 'paramilitary',
 'volunteer',
 'organisation',
 '.',
 'longest-serving',
 'prime',
 'minister',
 'outside',
 'Indian',
 'National',
 'Congress',
 '.',
 'Modi',
 'born',
 'raised',
 'Vadnagar',
 'northeastern',
 'Gujarat',
 ',',
 'completed',
 'secondary',
 'education',
 '.',
 'introduced',
 'RSS',
 'age',
 'eight',
 '.',
 'account',
 'helping',
 'father',
 'sell',
 'tea',
 'Vadnagar',
 'rail

In [25]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Create a vocabulary from the preprocessed words
vocabulary = list(set(lemmatized_words))  # Get unique words

# Initialize OneHotEncoder
encoder = OneHotEncoder(categories=[vocabulary])

# Reshape preprocessed_words for fitting to the encoder
reshaped_words = np.array(lemmatized_words).reshape(-1, 1)

# Fit and transform with OneHotEncoder
one_hot_encoded = encoder.fit_transform(reshaped_words).toarray()

print("One-Hot Encoded Representation:")
print(one_hot_encoded)


One-Hot Encoded Representation:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
from sklearn.feature_extraction.text import CountVectorizer

# Join preprocessed words back into a string (document)
preprocessed_text = ' '.join(stemmed_words)

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform with CountVectorizer
bow_representation = vectorizer.fit_transform([preprocessed_text])

# Convert BOW representation to array and get feature names
bow_array = bow_representation.toarray()
feature_names = vectorizer.get_feature_names_out()

print("Bag-of-Words Representation:")
print(bow_array)
print("Feature Names:")
print(feature_names)

Bag-of-Words Representation:
[[ 2  1  1  1  1  1  2  2  2  1  1  1  1  1  3  1  1  3  1  2  1  1  1  1
   1  1  1  1  1  2  1  1  1  1  1  1  6  2  2  1  1  1  2  1  1  1  1  1
   1  1  1  3  2  1  1  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1
   2  1  2  1  1  1  1  1  1  1  1  1  3  1  3  1  1  2  1  1  2  1  1  1
   1  1  1  1  1  1  1  1  1  1  3  1  1  5  1  2  1  1  1  1  2  2  1  1
   1  1  3  6  1  2  3  1  1  1  1  1  2  2  1  2  1  2  2  1  1  1  1  1
   1  1  1  2  1  5  1 13  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1
   1  4  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  2  1  4  1  1  1  1  1  1  1  2  1  1  1
   2  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  2
   1  1  1  1  1  1  1  1  1  1  1]]
Feature Names:
['000' '11' '14' '14th' '15' '16' '17' '18' '19' '1950' '1971' '1984'
 '1985' '20' '2001' '2002' '2012' '2014' '2016' '2019' '2020' '21' '22'
 '23' '24' '25' '26' 'abandon' 'aboli